apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickstream-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickstream-consumer
  template:
    metadata:
      labels:
        app: clickstream-consumer
    spec:
      restartPolicy: Always
      containers:
        - name: clickstream-consumer
          image: rahulkrish28/clickstream-consumer
          ports:
            - containerPort: 8002
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AWS_DEFAULT_REGION
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: SQS_QUEUE_URL
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_URI
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
